### ISSUE TITLE
Update from `wai` to `wit`

### ISSUE THREAD

**Issue by linclark** [WebAssembly/wit-abi-up-to-date#1]
Following up from the November 18th WASI meeting, this project should use the `wit` extension.

**Comment by sunfishcode** [comment]
https://github.com/WebAssembly/wit-abi-up-to-date/pull/2 implements the code changes for this.

**Comment by sunfishcode** [comment]
This is now implemented.

**Comment by linclark** [comment]
@sunfishcode I think we also need to create a new tag for v2
