### ISSUE TITLE
Failed to build `wit-abi` executable

### ISSUE THREAD

**Issue by abrown** [WebAssembly/wit-abi-up-to-date#4]
When converting the `wasi-nn` proposal over to the new WASI proposal template (https://github.com/WebAssembly/wasi-nn/pull/17), I added this GitHub action because it was a part of `wasi-filesystem`, which I used as an example. The action fails to install the `wit-abi` executable, though: https://github.com/WebAssembly/wasi-nn/runs/7010889446?check_suite_focus=true#step:3:211. I suspect this may be due to updates to `wit-abi` (maybe https://github.com/WebAssembly/wasi-tools/pull/3?) but no new Git tag.

I can attempt to fix this but wanted to record this here for @sunfishcode and @alexcrichton. How do we expect this action to work? Do we need to publish a new Git tag in `wit-abi` and then a similar tag in this action to keep things in sync?

**Comment by alexcrichton** [comment]
I think this was fixed in https://github.com/WebAssembly/wit-abi-up-to-date/pull/3 which should be under the v3 tag, which I believe can be done by updating [this line](https://github.com/WebAssembly/wasi-nn/pull/17/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R14)

**Comment by abrown** [comment]
This is fixed by https://github.com/WebAssembly/wasi-tools/issues/4; we can now use the `v4` version of this GitHub action which understands the latest syntax.
